//All actions list here
exports.GET_LATEST_ACTIVITY = 'GET_LATEST_ACTIVITY';
exports.POST_ACTIVITY = 'POST_ACTIVITY';
exports.POST_COMMENT_ON_ACTIVITY = 'POST_COMMENT_ON_ACTIVITY';
exports.UPDATE_ACTIVITY_LIST = 'UPDATE_ACTIVITY_LIST';

exports.GET_USER_PROFILE    = 'GET_USER_PROFILE';
exports.PATCH_USER_PROFILE = 'PATCH_USER_PROFILE';

exports.LOGIN_USER = 'LOGIN_USER';
exports.REGISTER_USER = 'REGISTER_USER';
